Add workaround for atexit cleanup
Until Python 3.5, Python destroys most of the world before the atexit
callback has a change to clean up. This leads to exceptions like:

Error in sys.exitfunc:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/home/heimes/dev/redhat/pyldap/Lib/slapdtest.py", line 303, in stop
    self._cleanup_rundir()
  File "/home/heimes/dev/redhat/pyldap/Lib/slapdtest.py", line 160, in _cleanup_rundir
    if not os.path.exists(self.testrundir):
AttributeError: 'NoneType' object has no attribute 'path'

import os, os.path to resurrect the os module.

Signed-off-by: Christian Heimes <cheimes@redhat.com>